---
- name: Create Certificates Directory
  become: true
  file:
    path: /opt/fsm/certs
    state: directory
    mode: '0755'

- name: Create NGINX & LE Companion Containers
  docker_compose:
    project_name: tls
    definition:
      version: '2'
      networks:
        default:
          external:
            name: fsm
      services:
        nginx-proxy:
          image: jwilder/nginx-proxy
          ports:
            - "80:80"
            - "443:443"
          volumes:
            - "/opt/fsm/certs:/etc/nginx/certs"
            - "/etc/nginx/vhost.d"
            - "/usr/share/nginx/html"
            - "/var/run/docker.sock:/tmp/docker.sock:ro"
          labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

        letsencrypt-nginx-proxy-companion:
          image: jrcs/letsencrypt-nginx-proxy-companion
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
          volumes_from:
            - "nginx-proxy"
